version: '3'
services:
  jupyter:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ./code:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
